tutorials/tutorial8/config/routes.rb
Rails.application.routes.draw do
  root "login#index"
  post "/handle_login", to: "login#validate_login"
  get "/handle_login", to: "login#handle_login"
end

tutorials/tutorial8/app/controllers/login_controller.rb
require "./config/initializers/constants.rb"
require "./config/initializers/messages.rb"
class LoginController < ApplicationController
  def validate_login
    if EMAIL === params[:email] && PASSWORD === params[:password]
      session[:email] = params[:email]
      session[:password] = params[:password]
      render "handle_login"
    elsif (params[:email] == "" || params[:password] == "")
      redirect_to root_path, alert: EMPTY
    else (params[:email] != EMAIL || params[:password] != PASSWORD)
      redirect_to root_path, alert: MISSMATCHED     end
  end
end

tutorials/tutorial8/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tutorials/tutorial8/app/views/login/handle_login.html.erb
<div class="form">
    <h1>Log_In Successfully.</h1>
    <button><%= link_to "Log_out", root_path %></button>
</div>

tutorials/tutorial8/app/views/login/index.html.erb
<div class="form">
  <h1>Login_Form</h1>
  <%= form_with url: handle_login_url, local: "true" do |form| %>
    <div class="input">
      <%= form.text_field :attr, name: "email", id: "email", placeholder: "Enter your email" %>
    </div>
    <div class="input">
      <%= form.password_field :attr, name: "password", id: "password", placeholder: "Enter your password" %>
    </div>
    <div class="button">
      <%= form.submit :login %>
    </div>

  <% end %>
</div>

<% flash.each do |type, msg| %>
  <div class="err">
   <%= msg %>
   </div>
<% end %>