tutorials/Assignment4/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection { post :import }
  end
  root "users#handle_login"
  resources :users
  post "/handle_login", to: "users#validate_login"
  post "/search_database", to: "users#search"
  get "/search_database", to: "users#index"
  get "/handle_login", to: "users#handle_login"
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  post "password/reset/edit", to: "password_resets#update"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

tutorials/Assignment4/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Post.create! row.to_hash
    end
  end
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |post|
        csv << post.attributes.values_at(*column_names)
      end
    end
  end
end

tutorials/Assignment4/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
    respond_to do |format|
      format.html
      format.csv { send_data @posts.to_csv, filename: "posts-#{Date.today}.csv" }
    end
  end

  def show
    @post = UserService.getUserByID(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @is_post_create = PostService.createPost(@post)
    if @is_post_create
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.js   
    end
    else
      render :new
    end

  end

  def edit
    @post = PostService.getPostByID(params[:id])
  end

  def update
    @post = PostService.getPostByID(params[:id])
    @is_post_update = PostService.updatePost(@post, post_params)
    if @is_post_update
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = PostService.getPostByID(params[:id])
    PostService.destroy(@post)

    respond_to do |format|
      format.html { redirect_to posts_path }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def import
    Post.import(params[:file])
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :status)
  end
end

tutorials/Assignment4/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = UserService.getUserByID(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @is_user_create = UserService.createUser(@user)
    if @is_user_create
      redirect_to users_path
    else
      render :new
    end
  end
 
  def edit
    @user = UserService.getUserByID(params[:id])
  end


  def update
    @user = UserService.getUserByID(params[:id])
    @is_user_update  = UserService.updateUser(@user,user_params)
    if  @is_user_update 
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = UserService.getUserByID(params[:id])
    UserService.destroy(@user)
    redirect_to users_path
  end
  
  def validate_login
    @user = User.find_by(email: params[:email])
    if @user == nil
      redirect_to root_path, notice: "Could not find the user"
    elsif @user.authenticate(params[:password])
      redirect_to users_path
    elsif @user.password != params[:password]
      redirect_to root_path , notice: "Email and Password Missmatched"
   end
  end
  
  
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :address, :phone_number)
  end
end

tutorials/Assignment4/app/views/posts/_post.html.erb
  <tr>
    <td><%= post.title %></td>
    <td><%= post.description %></td>
    <td><%= post.status %></td>
    <td>
      <%= link_to "Delete", post, method: :delete, data: { confirm: "Are you sure you want to delete this user?"}, class: "remove_post", :remote => true %>
    </td>
  </tr>

tutorials/Assignment4/app/views/posts/index.html.erb
<h1>Posts Data</h1>
<div class="createbtn">
<%=link_to "Create", new_post_path %>
</div>
<table>
  <thead>
    <th>title</th>
    <th>description</th>
    <th>status</th>
    <th>options</th>
  </thead>
  <tbody>
   <%= render @posts %>
  </tbody>
</table>

<%= form_with(model: @post, id: "new_post", local: false) do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>
<div>
  <%= f.label :status %>
  <%= f.radio_button :status, "1" %><label for="status_1">private</label>
  <%= f.radio_button :status, "0" %><label for="status_0">public</label>
</div>


<div>
  <%= f.submit %>
</div>
<% end %>




<h3>Import Posts</h3>
<%= form_tag import_posts_path,multipart: true do %>
 <%= file_field_tag :file%>
 <%= submit_tag "Upload Posts" %>
<% end %>

<h3>Download File</h3>
<%= link_to "Download", posts_path(format: "csv") %>

tutorials/Assignment4/app/views/users/index.html.erb
<h1>Users Data</h1>
<div class="createbtn">
<%=link_to "Create", new_user_path %>
</div>
<table>
  <thead>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>Phone number</th>
    <th>Operations</th>
  </thead>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.address %></td>
    <td><%= user.phone_number%></td>
    <td>
      <%= link_to "Edit", edit_user_path(user) %>
      <%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure you want to delete this user?"} %>
    </td>
  </tr>
  <% end %>
</table>